apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
      nodePort: 30020
  type: NodePort
  selector:
    service: frontend
#status:
#  loadBalancer: {}
